apiVersion: v1 
kind: Pod 
metadata: 
  name: todo-pod 
  labels: 
    env: test 
spec: 
  containers:
  - name: todo-container  
    image: ajeetraina/tod
    imagePullPolicy: IfNotPresent 
  nodeSelector: 
    mynode: worker-1
